app:
  storagedir: /opt/shortbin/storage
  dbpath: /opt/shortbin/config/shortbin.db
  baseurl: http://localhost
  cleanup: 0 1 * * * ?
spring:
  jpa:
    database-platform: ca.netopia.projects.shortbin.sqlite.SQLiteDialect
server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    use-relative-redirects: true
